// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateUserRequestDTO defines model for CreateUserRequestDTO.
type CreateUserRequestDTO struct {
	Email    openapi_types.Email `json:"email"`
	Phone    *string             `json:"phone,omitempty"`
	Username string              `json:"username"`
	Website  *string             `json:"website,omitempty"`
}

// GetUsersResponse defines model for GetUsersResponse.
type GetUsersResponse struct {
	Users *[]UserResponse `json:"users,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email    *string            `json:"email,omitempty"`
	Extra    *map[string]string `json:"extra,omitempty"`
	Id       *string            `json:"id,omitempty"`
	Name     *string            `json:"name,omitempty"`
	Phone    *string            `json:"phone,omitempty"`
	Username *string            `json:"username,omitempty"`
	Website  *string            `json:"website,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = CreateUserRequestDTO
