// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateUserRequestDTO defines model for CreateUserRequestDTO.
type CreateUserRequestDTO struct {
	Email    openapi_types.Email `json:"email"`
	Phone    *string             `json:"phone,omitempty"`
	Username string              `json:"username"`
	Website  *string             `json:"website,omitempty"`
}

// GetUsersResponse defines model for GetUsersResponse.
type GetUsersResponse struct {
	Users *[]UserResponse `json:"users,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Email    *string            `json:"email,omitempty"`
	Extra    *map[string]string `json:"extra,omitempty"`
	Id       *string            `json:"id,omitempty"`
	Name     *string            `json:"name,omitempty"`
	Phone    *string            `json:"phone,omitempty"`
	Username *string            `json:"username,omitempty"`
	Website  *string            `json:"website,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = CreateUserRequestDTO

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SUS2vbQBDHv0qY9tCCsJTmEvbWB5TQQkxoT8GHjTS2N2gfnhmlNUbfvczKUepI6aml",
	"Jw07j/3Pb2Z1gDr6FAMGYTAH4HqL3mbzI6EV/M5IN7jrkOXTt2s9TxQTkjjMUeita9VYR/JWwBxPCpB9",
	"QjDAQi5soC8gbWNADZ14OkYK1s87f+AdO5nz9QUQ7jpH2IC5fapSHDWsRhHx7h5r0WqfUbQlvkFOMTBO",
	"O9Iy2XCCPhuvCddg4FX5xKo8gioHPsda/XihJbL7rHCi4CTjZZ4TDvhTyKrHNo0TF4Ntlyepk4zJ1a6Z",
	"jXsR/b+Y2DNReuTCOuZgJ6368oDO3i+voIAHJHYxgIHzRbWotHxMGGxyYOBiUS0uoIBkZZsRlOPwNij6",
	"UT5WYV01YMbh5xSyHiVH3x7A6Q27DmkPjzwg2Y3u0jBpLeZdcL7zYM7HNlwQ3CBB3690GYepZgHvqko/",
	"dQyCIWuxKbWuzmrKe9aeDr8V/9OSTZY2Y2uQa3JJBjzXXzJe7ry3tAcDXx3L2cBDRxl5Bsgy8kiEhlf+",
	"ITb7vyZ89h/Snz5coQ77/wyvzjqbZwQH9ZnhG3475DHSw+PSdNSCga1IMmXZxtq228hiLqvLCvpV/ysA",
	"AP//edcgkVwFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
